proxies:
  - name: "NullNetWork-22-bot-1966313120-345527037-2.91GB📊-27D,4H⏳"
    type: "vless"
    server: null.psdgold.st
    port: 33341
    uuid: "72b7b770-04a3-4817-b7a9-59bbf844e117"
    network: "tcp"
    encryption: "none"
    udp: true

proxy-groups:
  - name: auto
    type: select
    proxies:
    - "NullNetWork-22-bot-1966313120-345527037-2.91GB📊-27D,4H⏳"

rules:
  - MATCH,auto
