proxies:
  - name: "ViP2-1060081146_9c4d"
    type: "vless"
    server: snapp.ir
    port: 80
    uuid: "ca4b3fc6-00fa-49f8-9d9a-95de96cbf918"
    network: "ws"
    encryption: "none"
    udp: true
    ws-opts:
      path: "/"
      headers:
        Host: "pan111e.redordead.ir"

proxy-groups:
  - name: auto
    type: select
    proxies:
    - "ViP2-1060081146_9c4d"

rules:
  - PROCESS-NAME,chrome.exe,auto
  - MATCH,DIRECT
