proxies:
  - name: "ViP🌿-1060081146_e744"
    type: "vless"
    server: snapp.ir
    port: 80
    uuid: "cdd630a6-2edc-4251-a576-8b50344a943f"
    network: "ws"
    encryption: "none"
    udp: true
    ws-opts:
      path: "/"
      headers:
        Host: "pan71e.nexoratechcenter.ir"

proxy-groups:
  - name: auto
    type: select
    proxies:
    - "ViP🌿-1060081146_e744"

rules:
  - PROCESS-NAME,chrome.exe,auto
  - MATCH,DIRECT
